LanguageCode = "ru-ru"
canonifyurls = "true"
SectionPagesMenu = "main"
pluralizeListTitles = "false"
Title = "Алексей Скульский. Тексты. Рассказы"
paginate = "10"
theme = "robust"
BaseURL = "/"

[Taxonomies]
tags = "tags"

[Params]
SyntaxHighlightTheme = "default.min.css"
Author = "Алексей Скульский"
ShowRelatedPost = "true"
ShowTagCloud = "true"
